// <auto-generated />
using System;
using AcademiaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademiaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AcademiaAPI.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AulasFeitas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AulasPlano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanoAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Aula", b =>
                {
                    b.Property<int>("IdAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confirmados")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAula")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAula");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Inscrito", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("IdAula")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.HasKey("IdAluno", "IdAula");

                    b.HasIndex("IdAula");

                    b.ToTable("Inscritos");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Inscrito", b =>
                {
                    b.HasOne("AcademiaAPI.Models.Aluno", "Aluno")
                        .WithMany("Inscricoes")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaAPI.Models.Aula", "Aula")
                        .WithMany("Inscricoes")
                        .HasForeignKey("IdAula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Aluno", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Aula", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
